.\"	$OpenBSD: mdoc.template,v 1.9 2004/07/02 10:36:57 jmc Exp $
.\"
.\" Copyright (c) 2007 GeNUA mbH <info@genua.de>
.\"
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
.\" TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
.\" PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
.\" LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\" NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" The following requests are required for all man pages.
.Dd September 16, 2009
.Dt ANOUBIS-KEYGEN 1
.Os Anoubis
.Sh NAME
.Nm anoubis-keygen
.Nd Creates an RSA key and certificate pair for Anoubis
.Sh SYNOPSIS
.Nm anoubis-keygen
.Op -h | --help
.Sh DESCRIPTION
The
.Nm
command generates an RSA private key and certificate for use with the Anoubis
Security Suite. The key should be encrypted with a passphrase. If you have root
privileges the script will install the certificate by copying it
to the
.Xr anoubisd 8
pubkeys directory.
.Pp
Options:
.Pp
.Bl -tag -width Ds
.It Fl h | -help
Prints a help message.
.Pp
.El
.Pp
.Sh AUTHORS
Daniela Zehetmeier
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh HISTORY
