.\"	$Id: 56550e,v 1.6 2008/01/22 15:48:08 hshoexer Exp $
.\"	$OpenBSD: mdoc.template,v 1.10 2007/05/31 22:10:19 jmc Exp $
.\"
.\" The following requests are required for all man pages.
.\"
.\" Remove `\&' from the line below.
.Dd $\&Mdocdate$
.Dt NAME SECTION#
.Os
.Sh ANOUBISD
.Nm anoubisd
.Nd Anoubis daemon
.Sh SYNOPSIS
.Nm anoubisd
.Op Fl dnv
.Sh DESCRIPTION
The
.Nm
is the backend daemon of the Anoubis Security Suite.
.Pp
The options are as follows:
.Bl -tag -wdith Ds
.It Fl d
When the
.Fl d
option is set,
.Nm
will run in debug mode in the foreground instead of daemonizing.
.It Fl n
Config test mode.
Only check the configuration file for validity.
.Nm
will do nothing except
.It Fl v
Produce more verbose output.
.El
.\" The following requests should be uncommented and used where appropriate.
.\" This next request is for sections 2, 3, and 9 function return values only.
.\" .Sh RETURN VALUES
.\" This next request is for sections 1, 6, 7 & 8 only.
.\" .Sh ENVIRONMENT
.\" .Sh FILES
.\" .Sh EXAMPLES
.\" This next request is for sections 1, 4, 6, and 8 only.
.\" .Sh DIAGNOSTICS
.\" The next request is for sections 2, 3, and 9 error and signal handling only.
.\" .Sh ERRORS
.\" .Sh SEE ALSO
.\" .Xr foobar 1
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
