/*
 * Copyright (c) 2009 GeNUA mbH <info@genua.de>
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _DLGRULEEDITORFILTERSUBJECTPAGE_H_
#define _DLGRULEEDITORFILTERSUBJECTPAGE_H_

#include "DlgRuleEditorBase.h"
#include "DlgRuleEditorPage.h"
#include "FilterPolicy.h"
#include "SfsFilterPolicy.h"
#include "SbAccessFilterPolicy.h"
#include "ContextFilterPolicy.h"

/**
 * This is the filter subject page.
 *
 * This page is responsible for SfsFilterPolicies and SbAccessFilterPolicies.
 *
 * This is a derrived class from DlgRuleEditorPage to inherrit the
 * mechanims of selection and deselection and observing the policy. In
 * addition we derrived from DlgRuleEditorFilterSubjectPageBase to gain
 * access to the widgets and implement the event methods of them.
 */
class DlgRuleEditorFilterSubjectPage : public DlgRuleEditorPage,
    public DlgRuleEditorFilterSubjectPageBase
{
	public:
		/**
		 * Constructor of the filter subject page.
		 * It has to have the same signature as a ordinary wxPanel,
		 * so wxformbuilder can just exchange wxPanel with this class.
		 */
		DlgRuleEditorFilterSubjectPage(wxWindow *parent,
		    wxWindowID id = wxID_ANY,
		    const wxPoint& pos = wxDefaultPosition,
		    const wxSize& size = wxDefaultSize,
		    long style = wxTAB_TRAVERSAL);

		/**
		 * Update the widgets.
		 * This is called whenever the assigned policy was modified
		 * or during selection to fill all widgets with the appropriate
		 * value.
		 * @param[in] 1st The policy been observed and modified.
		 * @return Nothing.
		 */
		virtual void update(Subject *);

		/**
		 * Select this page.
		 * This will check for the type of policy. If the policy is
		 * one of the types this page is interrested in the
		 * base class method will been called and this page is shown.
		 * @param[in] 1st The selected policy.
		 * @return Nothing.
		 */
		virtual void select(Policy *);

		/**
		 * Deselect this page.
		 * This will runn the base class method and hide this page.
		 * @param None.
		 * @return Noting.
		 */
		virtual void deselect(void);

		/**
		 * Set binary index.
		 * This page is responsible for handling the binary
		 * with the given index.
		 * @param[in] 1st Bianry index.
		 * @return Nothing.
		 */
		void setBinaryIndex(unsigned int);


	private:
		/**
		 * This holds the sfs policy being edited by this page.
		 */
		SfsFilterPolicy *sfsPolicy_;

		/**
		 * This holds the sb policy being edited by this page.
		 */
		SbAccessFilterPolicy *sbPolicy_;

		/**
		 * This holds the app policy being edited by this page.
		 */
		AppPolicy *appPolicy_;

		/**
		 * This holds the context filter policy being edited by
		 * this page.
		 */
		ContextFilterPolicy *ctxPolicy_;

		/**
		 * Update path widgets.
		 * This will take the value form the sfs policy.
		 * @param None.
		 * @return Nothing.
		 */
		void showSfsPath(void);

		/**
		 * Update path widgets.
		 * This will take the value form the sb policy.
		 * @param None.
		 * @return Nothing.
		 */
		void showSbPath(void);

		/**
		 * Update path widgets.
		 * This will take the value from the app policy.
		 * @param None.
		 * @return Nothing.
		 */
		void showAppPath(void);

		/**
		 * Update path widgets.
		 * This will take the value from the ctx filter policy.
		 * @param None.
		 * @return Nothing.
		 */
		void showCtxPath(void);

		/**
		 * Update subject widgets.
		 * @param None.
		 * @return Nothing.
		 */
		void showSubject(void);

		/**
		 * Handles events generated by selecting an item in
		 * subjectChoice.
		 * Depending on the selection the subjectTextCtrl-field on
		 * (de-)activated.
		 * @param[in] 1st The event.
		 * @return Nothing.
		 */
		virtual void onSubjectSelected(wxCommandEvent &);

		/**
		 * Handle events from subjectTextCtrl (on hit <enter>).
		 * Depending on the selection of subjectChoice the subject a
		 * subject is assigned to the policy.
		 * @param[in] 1st The event.
		 * @return Nothing.
		 */
		virtual void onSubjectTextEnter(wxCommandEvent &);

		/**
		 * Handle focus events from subjectTextCtrl (e.g on hit <tab>).
		 * Depending on the selection of subjectChoice the subject a
		 * subject is assigned to the policy.
		 * @param[in] 1st The event.
		 * @return Nothing.
		 */
		virtual void onSubjectTextKillFocus(wxFocusEvent &);

		/**
		 * This is the index of the app displayed in this page
		 * for app and ctx-filter Policies.
		 */
		unsigned int binaryIndex_;

	private:
		/**
		 * Set the subject to SELF/SELF-SIGNED.
		 * @param[in] 1st True if SELF_SIGNED is desired.
		 * @return None.
		 */
		void setSubjectSelf(bool);

		/**
		 * Set the subject UID. This also changes the subject type.
		 * @param[in] 1st The user ID.
		 * @return None.
		 */
		void setSubjectUid(uid_t uid);

		/**
		 * Set the subject KEY. This also changes the subject type.
		 * @param[in] 1st The Key ID.
		 * @return None.
		 */
		void setSubjectKey(wxString);

		/**
		 * Updates the subjectChoice-choice according to the
		 * information passed to the method.
		 * @param type Subject-type. The choice-entry with the assigned
		 *             type is selected.
		 * @param showAny If set to true, the any-entry is displayed.
		 */
		void updateSubjectChoice(int, bool);

		/**
		 * Updates the subjectTextCtrl-field according to the
		 * information passed to the method.
		 * @param enabled Set to true, if the field should be enabled.
		 * @param value The new value, which should be displayed.
		 */
		void updateSubjectTextCtrl(bool, const wxString &);
};

#endif	/* _DLGRULEEDITORFILTERSUBJECTPAGE_H_ */
