# $Id: 779c68,v 1.4 2007/11/23 16:05:21 ehrhardt Exp $

COMMENT=		anoubisd
V=			%%VERSION%%
DISTNAME=		anoubisd-${V}
PKGNAME=		${DISTNAME}
CATEGORIES=		security

MAINTAINER=		Hans-Joerg Hoexer <hshoexer@genua.de>

# BSD
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

NO_REGRESS=		Yes

WANTLIB +=		c
CONFIGURE_STYLE=	gnu

.include <bsd.port.mk>
